# Generated by Django 5.2.14 on 2026-10-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0004_customuser_subscription_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_first_login',
        ),
    ]
