# Generated by Django 5.2.14 on 2026-10-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0005_remove_customuser_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
